#Fuse Instalation Source

binary:
  folder: 'Users/yohanesws/RedHat/Installer/'

# Fuse Version and Patch
fuse:
  version: '6.3.0'
  patch: '187'
  maven_version: '630187' #fuse version 6.3.0 patch 187 --> 630187

# Patch Fuse Version and Patch
fuse_patch:
  version: '6.3.0'
  patch: '187'
  maven_version: '630187'

# OS User to install/execute Fuse
user:
  name: 'fuse'
  shell: '/bin/bash'
  homedir: 'True'

# OS Global Variables

# Java Home
java_home: /usr/lib/jvm/jre-1.8.0-openjdk

# Fuse Home
fuse_base: '/opt/fuse'
fuse_home: '{{ fuse_base }}/latest-{{ esb_name }}'

# Backups Paths
fuse_backup_path: /opt/fuse/backup

# Fuse Administrative Users
fuse_users:
  admin:
    username: admin
    password: karaf
    roles:
      - admin
      - manager
      - viewer
      - Monitor
      - Operator
      - Maintainer
      - Deployer
      - Auditor
      - Administrator
      - SuperUser
  deployer:
    username: deployer
    password: deployer
    roles:
      - Deployer
  guest:
    username: guest
    password: guest
    roles:
      - viewer
  amq:
    username: amq
    password: karaf
    roles:
      - viewer
      - Administrator

# Network of Brokers Multicast
nob_multicast_name: default

# KahaDB persistence store
kahadb_directory: /opt/fuse/kahadb

## Setup for Applications and Bundles

fuse_client: '{{ fuse_home }}/bin/client -r 3 -d 10 -u {{ fuse_users.admin.username }} -p {{ fuse_users.admin.password }}'

# Applications Home
app_home: '/opt/fuse/applications'

# maven_repository_manager: http://172.16.1.1:8381/artifactory/libs-snapshot

# Maven Repository
maven_repository:
  - 
    url: 'http://172.16.1.1:8381/artifactory/libs-release' 
    id: 'local.release'
    extra: ''
  - url: 'http://172.16.1.1:8381/artifactory/libs-snapshot'
    id: 'local.snapshot'
    extra: '@snapshots'
