---
- name: Fuse Deploy Bundles Playbook
  hosts: fuse-lab-environment
  vars_files:
    - vars/deploy.yml
  # remote_user: root
  gather_facts: true
  become: yes
  # become_user: root
  # become_method: sudo
  roles:
    # Deploying Bundles in Two Fuse Standalone
    - {
        role: fuse-deploy,
        esb_name: 'fuseesb',
        deploy_features: 'yes',
        deploy_bundles: 'yes',
        deploy_applications: 'yes'
      }
    # - {
    #     role: fuse-deploy,
    #     esb_name: 'fuseesb',
    #     deploy_features: 'no',
    #     deploy_bundles: 'no',
    #     deploy_applications: 'yes'
    #   }
    # - {
    #     role: fuse-deploy,
    #     esb_name: 'esb02',
    #     deploy_features: 'no',
    #     deploy_bundles: 'no',
    #     deploy_applications: 'yes'
    #   }
