---
# Playbook for Fuse Reload
- name: Fuse Reload Service Playbook
  vars:
    esb_names: 
     - "fuseesb"
  hosts: fuse-lab-environment
  gather_facts: true
  become: yes
  become_method: sudo
  tasks:
    - name: reload systemd
      command: systemctl daemon-reload

    - debug: 
        var: esb_names
        verbosity: 2

    - name: "reloaded fuse-{{ item }}"
      service: 
        name: "fuse-{{ item }}" 
        state: "started"
      with_items: "{{ esb_names }}"

